// Next.js API route support: https://nextjs.org/docs/api-routes/introduction
import type { NextApiRequest, NextApiResponse } from 'next'

export type LocalizedStrings = {
    appName: string,
    appDescription: string,
    confirm: string,
    map: string,
    settings: string,
    search: string,
    cancel: string,
    fromWhere: string,
    toWhere: string,
    date: string,
    time: string,
    interface: string,
    quickAccess: string,
    language: string,
    share: string,
    pwaSupport: string,
    activeDevelopment: string,
    slogan: string,
    wereBetterAt: string,
    interfaceSubtext: string,
    quickAccesSubtext: string,
    shareSubtext: string,
    pwaSupportSubtext: string,
    activeDevelopmentSubtext: string,
    searchSlogan: string,
    basicPreferences: string,
    discount: string,
    discountSubtext: string,
    calendarService: string,
    calendarServiceSubtext: string,
    recommendedForDevice: string,
    any: string,
    other: string,
    otherSettings: string,
    otherSettingsSubtext: string,
    routeLimit: string,
    routeLimitSubtext: string,
    routeLimitSubtext2: string,
    notRecommendedToDisable: string,
    visibleRunsOnMap: string,
    visibleRunsOnMapSubText: string,
    timelineType: string,
    timelineTypeSubtext: string,
    contentTransitions: string,
    contentTransitionsSubtext: string,
    contentTransitionsSubtext2: string,
    clearField: string,
    swapFields: string,
    clearFields: string,
    allFields: string,
    noRoutesAfterSelectedTime: string,
    transfer: string,
    mapView: string,
    timelineView: string,
    minute: string,
    operates: string,
    platform: string,
    donationGoal: string,
    donate: string,
    donateXofY: string,
    download: string,
    downloadTheApp: string,
    downloadPitch: string,
    error: string,
    pageNotFound: string,
    atArrival: string,
    timeForTransfer: string,
    settingsDownloadPitch: string,
    delay: string,
    languageSubtext: string,
    errorEmptyFields: string,
    errorEmptyFieldsSubtext: string,
    downloadApp: string,
    transitRoute: string,
    routesBeetweenXandY: string,
    timetables: string,
    and: string,
    stopsForX: string,
    realtimeTransitMap: string,
    realtimeTransitMapSubtext: string,
}

const strings: { hu: LocalizedStrings, en: LocalizedStrings } = {
    hu: {
        appName: "Menetrendek - A modern menetrend kereső",
        appDescription: "MÁV, Volánbusz, BKK, GYSEV, MAHART és BAHART menetrendek.",
        confirm: "Megerősítés",
        map: "Térkép",
        settings: "Beállítások",
        search: "Keresés",
        cancel: "Mégse",
        fromWhere: "Honnan?",
        toWhere: "Hova?",
        date: "Dátum",
        time: "Idő",
        interface: "Kezelőfelület",
        quickAccess: "Gyors elérés",
        language: "Nyelv",
        share: "Megosztás",
        pwaSupport: "PWA támogatás",
        activeDevelopment: "Aktív fejlesztés",
        slogan: "A modern menetrend kereső",
        wereBetterAt: "Íme néhány dolog, amiben jobbak vagyunk:",
        interfaceSubtext: "Modern, letisztult és mobilbarát kezelőfelület.",
        quickAccesSubtext: "Egyszerű megálló- és állomáskeresés, a legutóbbi elemek mentése gyors elérésbe.",
        shareSubtext: "Útvonaltervek gyors megosztása kép formájában.",
        pwaSupportSubtext: "Ez a weboldal egy PWA (progresszív webalkalmazás), így könnyen letöltheted alkalmazásként a telefonodra.",
        activeDevelopmentSubtext: "A weboldal szinte minden héten frissül. A funkciók folyamatosan bővülnek és a hibák folyamatosan javítva vannak.",
        searchSlogan: "A hasznos útitárs, aki végig kísér.",
        basicPreferences: "Alapvető preferenciák",
        discount: "Kedvezmény",
        discountSubtext: "Itt be tudod állítani, hogy hány százalékos kedvezménnyel utazol.",
        calendarService: "Naptár szolgáltatás",
        calendarServiceSubtext: "Itt kiválaszthatod, hogy melyik naptár szolgáltást használod.",
        recommendedForDevice: "Készülékedhez ajánlott",
        any: "Bármelyik",
        other: "Egyéb",
        otherSettings: "További beállítások",
        otherSettingsSubtext: "Ezekkel a beállításokkal jelentősebben befolyásolhatod az oldal működését.",
        routeLimit: "Útvonalterv limit",
        routeLimitSubtext: "Az egyszerre megjelenített útvonaltervek korlátozva vannak és egy időcsúszkával tudsz böngészni.",
        routeLimitSubtext2: "Az oldal annál gyorsabb, minél kevesebb jelenik meg egyszerre.",
        notRecommendedToDisable: "A funkció kikapcsolása nem ajánlott!",
        visibleRunsOnMap: "Látható járatok a térképen",
        visibleRunsOnMapSubText: "Korlátozza, hogy hány ikon jelenhet meg a térképen egyszerre.",
        timelineType: "Idővonal típusa",
        timelineTypeSubtext: "Itt választhatsz, hogy milyen típusú idővonal jelenjen meg az útvonalterveken.",
        contentTransitions: "Tartalom áttűnések",
        contentTransitionsSubtext: "Itt kikapcsolhatod az oldal tartalmának áttűnéseit.",
        contentTransitionsSubtext2: "A funkció kikapcsolása javíthatja az oldal teljesítményét.",
        clearField: "Mező törlése",
        swapFields: "Mezők felcserélése",
        clearFields: "Mezők törlése",
        allFields: "Minden mező",
        noRoutesAfterSelectedTime: "Nincs útvonal a kiválasztott időpont után",
        transfer: "átszállás",
        mapView: "Térkép nézet",
        timelineView: "Idővonal nézet",
        minute: "perc",
        operates: "Közlekedik:",
        platform: "Peron",
        donate: "Támogatás",
        donationGoal: "Jelenlegi cél",
        donateXofY: "{0}% az ${1}-ból",
        download: "Letöltés",
        downloadTheApp: "Töltsd le az alkalmazást!",
        downloadPitch: "Töltsd le a Menetrendek alkalmazást, hogy könnyen és gyorsan hozzáférj a menetrendekhez, a böngésződ megnyitása nélkül!",
        error: "Hiba!",
        pageNotFound: "Az oldal nem található!",
        atArrival: "érkezéskor",
        timeForTransfer: "Idő az átszállásra:",
        settingsDownloadPitch: "Még nem töltötted le az alkalmazást? Töltsd le most, hogy könnyen és gyorsan hozzáférj a menetrendekhez, a böngésződ megnyitása nélkül!",
        delay: "Késés",
        languageSubtext: "Itt választhatsz a rendelkezésre álló nyelvek közül.",
        errorEmptyFields: "Üres mezők!",
        errorEmptyFieldsSubtext: "Kérlek tölts ki minden mezőt a keresés megkezdéséhez!",
        downloadApp: "Alkalmazás letöltése",
        transitRoute: "Tömegközlekedési útvonal",
        routesBeetweenXandY: "Útvonalak {0} és {1} között",
        timetables: "menetrendek",
        and: "és",
        stopsForX: "{0} járat megállói",
        realtimeTransitMap: "Valós idejű tömegközlekedési térkép",
        realtimeTransitMapSubtext: "Tekintse meg Magyarország valós idejű tömegközlekedési térképét.",
    },
    en: {
        appName: "Menetrendek - Timetable search engine for Hungary",
        appDescription: "MÁV, Volánbusz, BKK, GYSEV, MAHART and BAHART timetables.",
        confirm: "Confirm",
        map: "Map",
        settings: "Setings",
        search: "Search",
        cancel: "Cancel",
        fromWhere: "From?",
        toWhere: "To?",
        date: "Date",
        time: "Time",
        interface: "Interface",
        quickAccess: "Quick access",
        language: "Language",
        share: "Share",
        pwaSupport: "PWA support",
        activeDevelopment: "Active development",
        slogan: "The modern timetable search engine",
        wereBetterAt: "Here are some things we're better at:",
        interfaceSubtext: "Modern, clean and mobile-friendly interface.",
        quickAccesSubtext: "Simple stop and station search, saving the last items to quick access.",
        shareSubtext: "Quick sharing of route plans in image form.",
        pwaSupportSubtext: "This website is a PWA (progressive web application), so you can easily download it as an application on your phone.",
        activeDevelopmentSubtext: "The website is updated almost every week. The features are constantly expanding and the bugs are constantly being fixed.",
        searchSlogan: "The useful travel companion who accompanies you all the way.",
        basicPreferences: "Basic preferences",
        discount: "Discount",
        discountSubtext: "Here you can set how much discount you travel with.",
        calendarService: "Calendar service",
        calendarServiceSubtext: "Here you can select which calendar service you use.",
        recommendedForDevice: "Recommended for your device",
        any: "Any",
        other: "Other",
        otherSettings: "Other settings",
        otherSettingsSubtext: "These settings can significantly affect the operation of the site.",
        routeLimit: "Route limit",
        routeLimitSubtext: "The displayed route plans are limited and you can browse with a time slider.",
        routeLimitSubtext2: "Less items displayed at once makes the site faster.",
        notRecommendedToDisable: "Disabling the function is not recommended!",
        visibleRunsOnMap: "Visible runs on the map",
        visibleRunsOnMapSubText: "Limits the number of icons that can appear on the map at once.",
        timelineType: "Timeline type",
        timelineTypeSubtext: "Here you can choose what type of timeline appears on the route plans.",
        contentTransitions: "Content transitions",
        contentTransitionsSubtext: "Here you can turn off the content transitions of the site.",
        contentTransitionsSubtext2: "Disabling the function can improve the site's performance.",
        clearField: "Clear field",
        swapFields: "Swap fields",
        clearFields: "Clear fields",
        allFields: "All fields",
        noRoutesAfterSelectedTime: "No routes after the selected time",
        transfer: "transfer(s)",
        mapView: "Map view",
        timelineView: "Timeline view",
        minute: "minute(s)",
        operates: "Operates:",
        platform: "Platform",
        donate: "Donate",
        donationGoal: "Current goal",
        donateXofY: "{0}% of ${1}",
        download: "Download",
        downloadTheApp: "Download the app!",
        downloadPitch: "Download the Menetrendek app to easily and quickly access the timetables without opening your browser!",
        error: "Error!",
        pageNotFound: "Page not found!",
        atArrival: "at arrival",
        timeForTransfer: "Time for transfer:",
        settingsDownloadPitch: "You haven't downloaded the app yet? Download it now to easily and quickly access the timetables without opening your browser!",
        delay: "Delay",
        languageSubtext: "Here you can choose from the available languages.",
        errorEmptyFields: "Empty fields!",
        errorEmptyFieldsSubtext: "Please fill in all fields to start the search!",
        downloadApp: "Download app",
        transitRoute: "Transit route",
        routesBeetweenXandY: "Routes between {0} and {1}",
        timetables: "timetables",
        and: "and",
        stopsForX: "Stops for {0}",
        realtimeTransitMap: "Realtime transit map",
        realtimeTransitMapSubtext: "View Hungary's realtime transit map.",
    }
}

export default function handler(
    req: NextApiRequest,
    res: NextApiResponse<any>
) {
    const lang: "hu" | "en" = JSON.parse(req.body).lang
    res.status(200).json(strings[lang])
}
