// Next.js API route support: https://nextjs.org/docs/api-routes/introduction
import type { NextApiRequest, NextApiResponse } from 'next'

const strings = {
    hu: {
        confirm: "Megerősítés",
        map: "Térkép",
        setings: "Beállítások",
        search: "Keresés",
        cancel: "Mégse",
        fromWhere: "Honnan?",
        toWhere: "Hova?",
        date: "Dátum",
        time: "Idő",
        interface: "Kezelőfelület",
        quickAccess: "Gyors elérés",
        language: "Nyelv",
        share: "Megosztás",
        pwaSupport: "PWA támogatás",
        activeDevelopment: "Aktív fejlesztés",
        slogan: "A modern menetrend kereső",
        wereBetterAt: "Íme néhány dolog, amiben jobbak vagyunk:",
        interfaceSubtext: "Modern, letisztult és mobilbarát kezelőfelület.",
        quickAccesSubtext: "Egyszerű megálló- és állomáskeresés, a legutóbbi elemek mentése gyors elérésbe.",
        shareSubtext: "Útvonaltervek gyors megosztása kép formájában.",
        pwaSupportSubtext: "Ez a weboldal egy PWA (progresszív webalkalmazás), így könnyen letöltheted alkalmazásként a telefonodra.",
        activeDevelopmentSubtext: "A weboldal szinte minden héten frissül. A funkciók folyamatosan bővülnek és a hibák folyamatosan javítva vannak.",
        searchSlogan: "A hasznos útitárs, aki végig kísér.",
        basicPreferences: "Alapvető preferenciák",
        discount: "Kedvezmény",
        discountSubtext: "Itt be tudod állítani, hogy hány százalékos kedvezménnyel utazol.",
        calendarService: "Naptár szolgáltatás",
        calendarServiceSubtext: "Itt kiválaszthatod, hogy melyik naptár szolgáltást használod.",
        recommendedForDevice: "Készülékedhez ajánlott",
        any: "Bármelyik",
        other: "Egyéb",
        otherSettings: "További beállítások",
        otherSettingsSubtext: "Ezekkel a beállításokkal jelentősebben befolyásolhatod az oldal működését.",
        routeLimit: "Útvonalterv limit",
        routeLimitSubtext: "Az egyszerre megjelenített útvonaltervek korlátozva vannak és egy időcsúszkával tudsz böngészni.",
        routeLimitSubtext2: "Az oldal annál gyorsabb, minél kevesebb jelenik meg egyszerre.",
        notRecommendedToDisable: "A funkció kikapcsolása nem ajánlott!",
        visibleRunsOnMap: "Látható járatok a térképen",
        visibleRunsOnMapSubText: "Korlátozza, hogy hány ikon jelenhet meg a térképen egyszerre.",
        timelineType: "Idővonal típusa",
        timelineTypeSubtext: "Itt választhatsz, hogy milyen típusú idővonal jelenjen meg az útvonalterveken.",
        contentTransitions: "Tartalom áttűnések",
        contentTransitionsSubtext: "Itt kikapcsolhatod az oldal tartalmának áttűnéseit.",
        contentTransitionsSubtext2: "A funkció kikapcsolása javíthatja az oldal teljesítményét.",
        clearField: "Mező törlése",
        swapFields: "Mezők felcserélése",
        clearFields: "Mezők törlése",
        allFields: "Minden mező",
        noRoutesAfterSelectedTime: "Nincs útvonal a kiválasztott időpont után",
        transfer: "átszállás",
        mapView: "Térkép nézet",
        timelineView: "Idővonal nézet",
        minute: "perc",
        operates: "Közlekedik:",
        platform: "Peron",
    },
    en: {
        confirm: "Confirm",
        map: "Map",
        setings: "Setings",
        search: "Search",
        cancel: "Cancel",
        fromWhere: "From?",
        toWhere: "To?",
        date: "Date",
        time: "Time",
        interface: "Interface",
        quickAccess: "Quick access",
        language: "Language",
        share: "Share",
        pwaSupport: "PWA support",
        activeDevelopment: "Active development",
        slogan: "The modern timetable search engine",
        wereBetterAt: "Here are some things we're better at:",
        interfaceSubtext: "Modern, clean and mobile-friendly interface.",
        quickAccesSubtext: "Simple stop and station search, saving the last items to quick access.",
        shareSubtext: "Quick sharing of route plans in image form.",
        pwaSupportSubtext: "This website is a PWA (progressive web application), so you can easily download it as an application on your phone.",
        activeDevelopmentSubtext: "The website is updated almost every week. The features are constantly expanding and the bugs are constantly being fixed.",
        searchSlogan: "The useful travel companion who accompanies you all the way.",
        basicPreferences: "Basic preferences",
        discount: "Discount",
        discountSubtext: "Here you can set how much discount you travel with.",
        calendarService: "Calendar service",
        calendarServiceSubtext: "Here you can select which calendar service you use.",
        recommendedForDevice: "Recommended for your device",
        any: "Any",
        other: "Other",
        otherSettings: "Other settings",
        otherSettingsSubtext: "These settings can significantly affect the operation of the site.",
        routeLimit: "Route limit",
        routeLimitSubtext: "The displayed route plans are limited and you can browse with a time slider.",
        routeLimitSubtext2: "Less items displayed at once makes the site faster.",
        notRecommendedToDisable: "Disabling the function is not recommended!",
        visibleRunsOnMap: "Visible runs on the map",
        visibleRunsOnMapSubText: "Limits the number of icons that can appear on the map at once.",
        timelineType: "Timeline type",
        timelineTypeSubtext: "Here you can choose what type of timeline appears on the route plans.",
        contentTransitions: "Content transitions",
        contentTransitionsSubtext: "Here you can turn off the content transitions of the site.",
        contentTransitionsSubtext2: "Disabling the function can improve the site's performance.",
        clearField: "Clear field",
        swapFields: "Swap fields",
        clearFields: "Clear fields",
        allFields: "All fields",
        noRoutesAfterSelectedTime: "No routes after the selected time",
        transfer: "transfer(s)",
        mapView: "Map view",
        timelineView: "Timeline view",
        minute: "minute",
        operates: "Operates:",
        platform: "Platform",
    }
}

export default function handler(
    req: NextApiRequest,
    res: NextApiResponse<any>
) {
    const { lang, request }: { lang: "hu" | "en", request: string[] } = JSON.parse(req.body)
    let response: any = {}
    Object.keys(strings[lang]).map((key: any) => {
        if (request.includes(key)) {
            response[key] = (strings[lang] as any)[key]
        }
    })
    res.status(200).json(response)
}
